// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { PrismaPg } from '@prisma/adapter-pg';

const url =
  process.env['DATABASE_URL'] ??
  'postgresql://postgres:postgres@localhost:5432/moongatracker';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url,
    adapter: () => new PrismaPg({ connectionString: url }),
  },
});
